name: Get JavaDoc matrix
inputs:
  release-type:
    description: 'Type of Edition ALL|OSS|EE'
    required: false

outputs:
  json:
    value: ${{ steps.compute-matrix.outputs.json }}

runs:
  using: composite
  steps:
      - name: Resolve editions
        id: resolve-editions
        uses: hazelcast/docker-actions/resolve-editions@master
        with:
          release-type: ${{ inputs.release-type }}

      - name: Compute edition type matrix
        id: compute-matrix
        shell: bash
        run: |
          oss_template='{
            "label": "oss",
            "local-root": "hazelcast",
            "remote-root": "hazelcast-docs",
            "mvn-options": ""
          }'

          ee_template='{
            "label": "ee",
            "local-root": ".",
            "remote-root": "hazelcast-ee-docs",
            "mvn-options": "-P-os-hazelcast"
          }'

          editions=()
        
          if [[ "${{ steps.resolve-editions.outputs.should_build_oss }}" == "true" ]]; then
              editions+=($(echo "$oss_template" | jq --compact-output '.'))
          fi

          if [[ "${{ steps.resolve-editions.outputs.should_build_ee }}" == "true" ]]; then
              editions+=($(echo "$ee_template" | jq --compact-output '.'))
          fi

          json="[$(IFS=,; echo "${editions[*]}")]"

          echo "AAAAAAAAA ${{ inputs.release-type }} ######### ${json}"
          echo "json=${json}" >> "$GITHUB_OUTPUT"
