name: 'Gets various Mono version info'
description: |
  Evaluates and outputs Mono related version info used in other workflows e.g. hazelcast 
  version updates in docs repos. The action checkouts out Mono locally
inputs:
  release-version:
    description: 'The release version in progress'
    required: true
  github-token:
    description: 'The GitHub authentication token used for the GitHub CLI'
    required: true

outputs:
  master-version:
    description: 'The version parsed from master pom'
    value: ${{ steps.evaluate-version.outputs.master-version }}
  major-minor-ver:
    description: 'The major.minor parts of release-version'
    value: ${{ steps.evaluate-version.outputs.major-minor-ver }}
  is-next-release-major:
    description: 'Checks if next pom version is a MAJOR e.g. 9.0.0'
    value: ${{ steps.evaluate-version.outputs.is-next-release-major }}
  is-latest-stable-release:
    description: 'Returns true `release-version` (major.minor) is latest'
    value: ${{ steps.evaluate-version.outputs.is-latest-stable-release }}
  is-beta-release:
    description: 'Returns true if `release-version` has `*-BETA-*` in the name'
    value: ${{ steps.evaluate-version.outputs.is-beta-release }}
  is-major-minor:
    description: 'Returns true if the patch component of release-version is zero'
    value: ${{ steps.evaluate-version.outputs.is-major-minor }}

runs:
  using: 'composite'
  steps:
    - name: Generate Random Directory Name
      id: tmpdir
      shell: bash
      run: |
        echo "name=mono-temp.${RANDOM}" >> ${GITHUB_OUTPUT}

    - name: Checkout Hazelcast Mono
      uses: actions/checkout@v7
      with:
        repository: ${{ github.repository_owner }}/hazelcast-mono
        path: ${{ steps.tmpdir.outputs.name }}
        token: ${{ inputs.github-token }}
        fetch-depth: 1

    - name: Run Version Evaluations
      id: evaluate-version
      shell: bash
      run: |
        set -o errexit -o nounset -o pipefail ${RUNNER_DEBUG:+-x}

        source "${GITHUB_ACTION_PATH}/scripts/get.version.info.sh"

        master_ver=$(get_master_version ${mono_path})
        next_major=$(is_master_version_major ${release_version} ${master_ver})
        latest_stable=$(is_latest_stable_release ${release_version} ${repo_owner})
        beta_release=$(is_beta_release ${release_version})
        major_minor=$(is_major_minor ${release_version})
        major_minor_parts=$(get_major_minor_parts ${release_version})

        echo "master-version=${master_ver}" >> ${GITHUB_OUTPUT}
        echo "is-next-release-major=${next_major}" >> ${GITHUB_OUTPUT}
        echo "is-latest-stable-release=${latest_stable}" >> ${GITHUB_OUTPUT}
        echo "is-beta-release=${beta_release}" >> ${GITHUB_OUTPUT}
        echo "is-major-minor=${major_minor}" >> ${GITHUB_OUTPUT}
        echo "major-minor-ver=${major_minor_parts}" >> ${GITHUB_OUTPUT}
      env:
        release_version: ${{ inputs.release-version }}
        repo_owner: ${{ github.repository_owner }}
        gh_token: ${{ inputs.github-token }}
        mono_path: ${{ steps.tmpdir.outputs.name }}
