name: Test resolve-javadoc-deploy-config action

on:
  workflow_call:

jobs:
  test:
    runs-on: ubuntu-latest
    env:
      RELEASE_VERSION: '5.5.5'
    steps:
      - name: Checkout repository
        uses: actions/checkout@v6

      - name: Resolve JavaDoc deploy config (ALL)
        id: resolve-javadoc-deploy-config-all
        uses: ./resolve-javadoc-deploy-config
        with:
          release-version: ${{ env.RELEASE_VERSION }}
          release-type: 'ALL'

      - name: Resolve JavaDoc deploy config (OSS)
        id: resolve-javadoc-deploy-config-oss
        uses: ./resolve-javadoc-deploy-config
        with:
          release-version:  ${{ env.RELEASE_VERSION }}
          release-type: 'OSS'

      - name: Resolve JavaDoc deploy config (EE)
        id: resolve-javadoc-deploy-config-ee
        uses: ./resolve-javadoc-deploy-config
        with:
          release-version:  ${{ env.RELEASE_VERSION }}
          release-type: 'EE'

      - name: Test outputs
        run: |
          source /dev/stdin <<< "$(curl --silent https://raw.githubusercontent.com/hazelcast/assert.sh/main/assert.sh)"

          TESTS_RESULT=0

          assert_field_by_label() {
              # Generic function to test single JSON field by label. The same field will exist
              # for 'ALL' and the test asserts the field against expected label
              local label=$1
              local field=$2
              local field_value=$3
              local matrix=$4

              local has_field=$(echo "${matrix}" | jq \
                  --arg field "${field}" \
                  --arg fieldVal "${field_value}" \
                  --arg lbl "${label}" \
                  'any(.[]; .[$field] == $fieldVal and .label == $lbl)')

              assert_true "${has_field}" "'${field}=${field_value}' is missing/incorrect for label '${label}'" || TESTS_RESULT=$?
          }

          assert_label() {
              local label=$1
              local actual_matrix=$2
              local has_label=$(echo "${actual_matrix}" | jq --arg lbl "${label}" 'any(.[]; .label == $lbl)')
              assert_true "${has_label}" "label '${label}' is missing" || TESTS_RESULT=$?
          }

          # Assert 'label'
          assert_label 'oss' '${{ steps.resolve-javadoc-deploy-config-oss.outputs.json }}'
          assert_label 'oss' '${{ steps.resolve-javadoc-deploy-config-all.outputs.json }}'
          assert_label 'ee' '${{ steps.resolve-javadoc-deploy-config-all.outputs.json }}'
          assert_label 'ee' '${{ steps.resolve-javadoc-deploy-config-ee.outputs.json }}'

          FIELD="remote-root"
          assert_field_by_label 'oss' "${FIELD}" 'hazelcast-docs' '${{ steps.resolve-javadoc-deploy-config-oss.outputs.json }}'
          assert_field_by_label 'oss' "${FIELD}" 'hazelcast-docs' '${{ steps.resolve-javadoc-deploy-config-all.outputs.json }}'
          assert_field_by_label 'ee' "${FIELD}" 'hazelcast-ee-docs' '${{ steps.resolve-javadoc-deploy-config-ee.outputs.json }}'
          assert_field_by_label 'ee' "${FIELD}" 'hazelcast-ee-docs' '${{ steps.resolve-javadoc-deploy-config-all.outputs.json }}'

          FIELD="local-root"
          assert_field_by_label 'oss' "${FIELD}" 'hazelcast' '${{ steps.resolve-javadoc-deploy-config-oss.outputs.json }}'
          assert_field_by_label 'oss' "${FIELD}" 'hazelcast' '${{ steps.resolve-javadoc-deploy-config-all.outputs.json }}'
          assert_field_by_label 'ee' "${FIELD}" '.' '${{ steps.resolve-javadoc-deploy-config-ee.outputs.json }}'
          assert_field_by_label 'ee' "${FIELD}" '.' '${{ steps.resolve-javadoc-deploy-config-all.outputs.json }}'

          FIELD="jar-folder"
          assert_field_by_label 'oss' "${FIELD}" 'hazelcast/target' "${json_oss}"
          assert_field_by_label 'oss' "${FIELD}" 'hazelcast/target' "${json_all}"
          assert_field_by_label 'ee' "${FIELD}" './target' "${json_ee}"
          assert_field_by_label 'ee' "${FIELD}" './target' "${json_all}"

          FIELD="jar-file"
          assert_field_by_label 'oss' "${FIELD}" "hazelcast-root-${RELEASE_VERSION}-javadoc.jar" "${json_oss}"
          assert_field_by_label 'oss' "${FIELD}" "hazelcast-root-${RELEASE_VERSION}-javadoc.jar" "${json_all}"
          assert_field_by_label 'ee' "${FIELD}" "hazelcast-enterprise-root-${RELEASE_VERSION}-javadoc.jar" "${json_ee}"
          assert_field_by_label 'ee' "${FIELD}" "hazelcast-enterprise-root-${RELEASE_VERSION}-javadoc.jar" "${json_all}"

          FIELD="mvn-options"
          assert_field_by_label 'oss' "${FIELD}" '' '${{ steps.resolve-javadoc-deploy-config-oss.outputs.json }}'
          assert_field_by_label 'oss' "${FIELD}" '' '${{ steps.resolve-javadoc-deploy-config-all.outputs.json }}'
          assert_field_by_label 'ee' "${FIELD}" '-P-os-hazelcast' '${{ steps.resolve-javadoc-deploy-config-ee.outputs.json }}'
          assert_field_by_label 'ee' "${FIELD}" '-P-os-hazelcast' '${{ steps.resolve-javadoc-deploy-config-all.outputs.json }}'

          assert_eq 0 "$TESTS_RESULT" "All tests should pass"
