name: Test setup-maven action

on:
  workflow_call:

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v6

      - name: Get matrix (ALL)
        id: get-javadoc-matrix-all
        uses: ./get-javadoc-matrix
        with:
          release-type: 'ALL'

      - name: Get matrix (OSS)
        id: get-javadoc-matrix-oss
        uses: ./get-javadoc-matrix
        with:
          release-type: 'OSS'

      - name: Get matrix (EE)
        id: get-javadoc-matrix-ee
        uses: ./get-javadoc-matrix
        with:
          release-type: 'EE'

      - name: Test outputs
        run: |
          source /dev/stdin <<< "$(curl --silent https://raw.githubusercontent.com/hazelcast/assert.sh/main/assert.sh)"

          assert_label() {
            local label=$1
            local actual_matrix=$2
            local has_matrix=$(echo "${actual_matrix}" | jq --arg lbl "$label" 'any(.[]; .label == $lbl)')
            assert_true "${has_matrix}" "'${label}' label is missing"
          }

          assert_matrix() {
            local rel_type=$1
            local actual_matrix=$2
            
            if [[ "${rel_type}" =~ ALL|OSS ]]; then
              assert_label "oss" "${actual_matrix}"
            fi

            if [[ "${rel_type}" =~ ALL|EE ]]; then
              assert_label "ee" "${actual_matrix}"
            fi
          }

          assert_matrix 'ALL' '${{ steps.get-javadoc-matrix-all.outputs.json }}'
          assert_matrix 'OSS' '${{ steps.get-javadoc-matrix-oss.outputs.json }}'
          assert_matrix 'EE' '${{ steps.get-javadoc-matrix-ee.outputs.json }}'
